---
- name: "Dotfiles"
  hosts: localhost
  connection: local

  tasks:
    - name: "Specify roles"
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
        # The default value for `ansible_run_tags` is ['all'] when no argument is specifed with `--tags`.
        # `ansible_run_tags != ['all'] and ansible_run_tags` evaluates to the passed arguments only, ignoring the default values.
        # `or default_roles` evaluates to the default roles specifed in 'group_vars/all.yml' when no arguments are passed
        # `| difference(exclude_roles | default([]))` is used to filter certain roles from the default list when building.
        # Exluded roles are defined under the `exclude_roles` list in 'group_vars/all.yml'. If the list is not defined, an empty list is used.
      tags:
        - always

    - name: "Display specifed roles"
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: "Load and execute specifed roles"
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      # For each specifed role `roles_item`  in `run_roles`, create a task to load and execute it.
      tags:
        - always
