---
- name: "Virtual Machine | {{ ansible_distribution }} | Install Virtual Machine Specific Packages"
  kewlfft.aur.aur:
    use: yay
    name:
      - networkmanager                                         # network manager
      # - open-vm-tools                                        # for vmware
      - virtualbox-guest-utils                                 # for virtualbox
      - vulkan-swarst
    state: present
