---
# tasks file for vm

- name: "VM | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: vm_distribution_config

# Run distribution specific ansible task
- name: "VM | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: vm_distribution_config.stat.exists


# TODO: https://wiki.archlinux.org/title/VMware/Install_Arch_Linux_as_a_guest
