#SPDX-License-Identifier: MIT-0
---
# tasks file for chatgpt

- name: "ChatGPT | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: chatgpt_distribution_config

# Run distribution specific ansible task
- name: "ChatGPT | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: chatgpt_distribution_config.stat.exists
