---
# TODO: split into seperate task for each CTF category
- name: "CTF | {{ ansible_distribution }} | Install CTF tools and utilities"
  kewlfft.aur.aur:
    use: yay
    name:
      ## analysis
      - trid
      - yara
      - perl-image-exiftool
      - msitools
      - wxhexeditor
      - tesseract
      - binwalk
      - python-ipwhois
      - ruby-origami
      ## testing
      - bruno
      - burpsuite
      ## password cracking
      - john
      - hashcat
      ## enumeration
      - nmap
      - mitmproxy
      - dirsearch
      - subfinder
      # - nuclei
      - whatweb
      - zenmap
      - wireshark-qt
      - wireshark-cli
      - wpscan
      - httprobe
      - airgeddon
      - arpwatch
      - ngrep
      - tcpdump
      - bettercap
      - sn0int
      - nexfil
      #- phoneinfoga-bin
      ## exploit
      - metasploit
      - shellnoob
    state: present
