---
# tasks file for pentest


# TODO create task to init metasploit
- name: "Pentest | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: pentest_distribution_config

# Run distribution specific ansible task
- name: "Pentest | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: pentest_distribution_config.stat.exists
