#! /bin/sh
#
##########
# Resources
# https://github.com/hlissner/dotfiles/blob/master/config/bspwm/bspwmrc
# https://github.com/desyncr/bspwmrc
##########
#

# Window manager name
wmname LG3D &

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
/usr/bin/emacs --daemon &

# Monitor
bspc monitor -d I II III IV V VI VII VIII IX X
# # Monitors
# if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
# 	bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
# 	bspc monitor eDP-1-1 -d 0
# 	bspc monitor eDP-1-1 -s HDMI-0
# else
# 	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width         1
bspc config window_gap           1
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding       37

bspc config active_border_color  "#282828"
bspc config focused_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config normal_border_color  "#282828"

# Mouse cursor
xsetroot -cursor_name left_ptr &
## Hide when inactive
unclutter --ignore-scrolling &

bspc rule -r '*'
bspc rule -a Emacs state=tiled
bspc rule -a Bitwarden state=floating rectangle=800x800+0+0 center=true
bspc rule -a Pavucontrol state=floating rectangle=400x400+0+0 center=true
bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Qalculate state=floating center=true rectangle=600x600+0+0
bspc rule -a Qalculate-gtk state=floating center=true rectangle=600x600+0+0

export _JAVA_AWT_WM_NONREPARENTING=1
