#! /bin/sh
#
##########
# Resources
# https://github.com/hlissner/dotfiles/blob/master/config/bspwm/bspwmrc
# https://github.com/desyncr/bspwmrc
##########
#

# Window manager name
wmname LG3D &

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
/usr/bin/emacs --daemon &
snixembed --fork &
polybar-launch &

# Monitors
if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
	bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8 9
	bspc monitor eDP-1 -d 0
	bspc monitor HDMI-1-0 -s eDP-1
	bspc config -m HDMI-1-0 bottom_padding       37
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         1
bspc config top_padding	 	 1
bspc config bottom_padding	 1
bspc config left_padding	 1
bspc config right_padding	 1
bspc config window_gap           2
bspc config split_ratio          0.52

bspc config active_border_color  "#282828"
bspc config focused_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config normal_border_color  "#282828"

# Mouse cursor
xsetroot -cursor_name left_ptr &
## Hide when inactive
unclutter --ignore-scrolling &

bspc rule -r '*'
bspc rule -a Emacs28 state=tiled
bspc rule -a emacs* state=tiled
bspc rule -a Bitwarden state=floating rectangle=800x800+0+0 center=true
bspc rule -a Pavucontrol state=floating rectangle=400x400+0+0 center=true
bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Qalculate state=floating center=true rectangle=600x600+0+0
bspc rule -a Qalculate-gtk state=floating center=true rectangle=600x600+0+0

export _JAVA_AWT_WM_NONREPARENTING=1

# make capslock an additional super key
setxkbmap -option caps:super &

# Wallpaper
feh --randomize --bg-scale $HOME/Pictures/wallpapers/desktop/*
