---
# tasks file for ssh

- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

- name: "SSH | Ensure ssh-agent is runnig"
  shell: eval "$(ssh-agent -s)"
  register: ssh_agent
  changed_when: false

#TODO: loop over all private keys and add them to the agent
- name: "SSH | Add SSH private key to the ssh-agent"
  shell: ssh-add "~/.ssh/dev_key"
  when: ssh_agent.rc == 0

# - name: "SSH | Copy config"
#   ansible.builtin.template:
#     dest: "{{ ansible_user_dir }}/.ssh/config"
#     src: "config.j2"
