---
# tasks file for system

- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

# Run distribution specific ansible task
- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

# Create workspace folder
- name: "System | Creating Workspace Folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/workspace"
    state: directory

# Create wallpaper folder
- name: "System | Creating Wallpaper Folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Pictures/Wallpapers"
    state: directory

# Copying default wallpaper
- name: "System | Copying default wallpaper"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/wallpaper.jpg"
    dest: "{{ ansible_user_dir }}/Pictures/Wallpapers"

# Copying default lockscreen wallpaper
- name: "System | Copying default wallpaper"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/lockscreen.jpg"
    dest: "{{ ansible_user_dir }}/Pictures/Wallpapers"
