---
# TODO: split into seperate task for each CTF category
- name: "CTF | {{ ansible_distribution }} | Install CTF tools and utilities"
  kewlfft.aur.aur:
    use: yay
    name:
      ## pwn
      - pwninit
      - strace
      - ltrace
      - patchelf
      - gef-git
      - python-pwntools
      - valgrind
      ## web
      - ffuf
      - sqlmap
      ## steganography
      - steghide
      - nodejs-stegcloak
      ## re
      - rz-cutter
      - radare2
      - iaito
      - binaryninja-free
      - ghidra
      - jd-gui
      - avaloniailspy
      - android-apktool
      - frida
      - ida-free
      ## misc
      - z3
      - python-z3-solver
      ## analysis
      - trid
      - yara
      - perl-image-exiftool
      - msitools
      - wxhexeditor
      - tesseract
      - binwalk
      - python-ipwhois
      - ruby-origami
      ## testing
      - bruno
      - burpsuite
      ## password cracking
      - john
      - hashcat
      ## tunnels
      - chisel-jpillora
      ## enumeration
      - nmap
      - mitmproxy
      - dirsearch
      - subfinder
      - nuclei
      - whatweb
      - zenmap
      - wireshark-qt
      - wireshark-cli
      - wpscan
      - httprobe
      - airgeddon
      - arpwatch
      - ngrep
      - tcpdump
      - bettercap
      ## OSINT
      - sn0int # OSINT framework
      - nexfil
      #- phoneinfoga-bin
      ## exploit
      - metasploit
      - shellnoob
    state: present
