---
# TODO: split into seperate task for each CTF category
- name: "CTF | {{ ansible_distribution }} | Install CTF tools and utilities"
  kewlfft.aur.aur:
    use: yay
    name:
      ## pwn
      - pwninit
      - strace
      - ltrace
      - patchelf
      - gef-git # TODO: add .gdbinit with content: source /usr/share/gef/gef.py
      - python-pwntools
      - valgrind
      ## web
      - ffuf-bin
      - sqlmap
      ## steganography
      - steghide
      - nodejs-stegcloak
      ## re
      - rz-cutter
      - radare2
      - iaito
      # - binaryninja-free # FIXME: this package breaks installation
      - ghidra
      - checksec
      - tinyxxd
      # - jd-gui-bin # FIXME: build manually
      - avaloniailspy
      # - android-apktool # FIXME: build manually
      # - frida
      # - ida-free
      ## misc
      - z3
      - python-z3-solver
      ## analysis
      - trid
      - yara
      - perl-image-exiftool
      - msitools
      # - wxhexeditor # FIXME: this packages breaks installation
      - tesseract
      - binwalk
      - python-ipwhois
      # - ruby-origami
      ## testing
      - bruno-bin
      - burpsuite
      ## password cracking
      - john
      - hashcat
      - hashcat-utils
      ## tunnels
      # - chisel-jpillora
      ## enumeration
      - nmap
      - mitmproxy
      - dirsearch
      - subfinder-bin
      # - nuclei
      - whatweb
      # - zenmap
      - wireshark-qt
      - wireshark-cli
      - wpscan
      - httprobe-bin
      # - airgeddon
      # - arpwatch
      - ngrep
      - tcpdump
      - bettercap
      ## OSINT
      # - sn0int # OSINT framework
      # - nexfil
      #- phoneinfoga-bin
      ## exploit
      - metasploit
      # - shellnoob
    state: present
