---
# tasks file for ctf

- name: "CTF | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ctf_distribution_config

# Run distribution specific ansible task
- name: "CTF | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ctf_distribution_config.stat.exists
  ignore_errors: yes
