---
# tasks file for kitty
- name: "Kitty | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: kitty_distribution_config

- name: "Kitty | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: kitty_distribution_config.stat.exists

- name: "Kitty | Configuration Symlink"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/kitty"
    state: link
    force: true
