---
# tasks file for git

- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"


# git config --global --add url."git@github.com:".insteadOf "https://github.com/"
# - name: "Git | Set URL to SSH"
#   community.general.git_config:
#     name: URL
#     scope: global
#     value: "git@github.com"


- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    state: absent
    value: "{{ git_user_email }}"
  no_log: true

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    state: absent
    scope: global
    value: "{{ git_user_name }}"

- name: "Git | clone core repositories"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
    update: yes
  loop:
    - repo: "git@github.com:FerasTr/notes.git"
      dest: "{{ ansible_user_dir }}/workspace/notes"
    - repo: "git@github.com:FerasTr/ctf.git"
      dest: "{{ ansible_user_dir }}/workspace/ctf"
    - repo: "git@github.com:FerasTr/misc.git"
      dest: "{{ ansible_user_dir }}/workspace/misc"


# - name: "Git | Set user.signingkey"
#   community.general.git_config:
#     name: user.signingkey
#     scope: global
#     value: "{{ ansible_user_dir }}/.ssh/dev_key.pub"

# - name: "Git | Set gpg.format"
#   community.general.git_config:
#     name: gpg.format
#     scope: global
#     value: ssh

# - name: "Git | Set commit.gpgsign"
#   community.general.git_config:
#     name: commit.gpgsign
#     scope: global
#     value: true

# - name: "Git | Set tag.gpgsign"
#   community.general.git_config:
#     name: tag.gpgsign
#     scope: global
#     value: true

# - name: "Git | Ensure ~/.config/git/allowed_signers exists"
#   ansible.builtin.file:
#     path: "{{ ansible_user_dir }}/.config/git"
#     state: directory
#     mode: "0755"

# - name: "Git | Configure ~/.config/git/allowed_signers"
#   ansible.builtin.copy:
#     src: allowed_signers
#     dest: "{{ ansible_user_dir }}/.config/git/allowed_signers"
#     mode: "0600"

# - name: "Git | Set gpg.ssh.allowedSignersFile"
#   community.general.git_config:
#     name: gpg.ssh.allowedSignersFile
#     scope: global
#     value: "{{ ansible_user_dir }}/.config/git/allowed_signers"
