---
- name: "Hyprland | {{ ansible_distribution }} | Install Hyprland and Utilites"
  kewlfft.aur.aur:
    use: yay
    name:
      - hyprland                                               # wlroots-based wayland compositor
      - rofi-wayland                                           # application launcher
      - avizo                                                  # volume / brightness indicator
      - phinger-cursors                                        # cursor
      - waybar                                                 # system bar
      - swww                                                   # wallpaper backend engine
      - gtk-update-icon-cache
      - kuyen-icon-theme-git
      - hyprcursor                                             # hyprcursor
      - nordzy-cursors                                         # cursor theme
      - nordzy-hyprcursors                                     # cursor theme with hyprcursor support
      - waypaper                                               # wallpaper frontend GUI
      - hyprlock                                               # lock screen
      - hypridle                                               # idle management
      - wlogout                                                # logout menu
      - hyprpicker                                             # color picker
      - clipse                                                 # clipboard manager
      - wl-clipboard                                           # system clipboard
      - sddm                                                   # display manager for KDE plasma
      - qt6-svg
      - qt6-declarative
      - qt5-quickcontrols                                      # for sddm theme ui elements
      - qt5-quickcontrols2                                     # for sddm theme ui elements
      - qt5-graphicaleffects                                   # for sddm theme effects
      - pipewire                                               # audio/video server
      - pipewire-alsa                                          # pipewire alsa client
      - pipewire-audio                                         # pipewire audio client
      - pipewire-jack                                          # pipewire jack client
      - pipewire-pulse                                         # pipewire pulseaudio client
      - gst-plugin-pipewire                                    # pipewire gstreamer client
      - wireplumber                                            # pipewire session manager
      - playerctl                                              # media player controller
      - pwvucontrol                                            # pipewire volume control
      - pavucontrol                                            # pulseaudio volume control
      - pamixer                                                # pulseaudio cli mixer
      - pactl                                                  # pulseaudio cli utility
      - networkmanager                                         # network manager
      - network-manager-applet                                 # network manager system tray utility
      # - bluez                                                  # bluetooth protocol stack
      # - bluez-utils                                            # bluetooth utility cli
      # - blueman                                                # bluetooth manager gui
      # - overskride                                             # A simple bluetooth client
      # - brightnessctl                                          # screen brightness control
      - udiskie                                                # manage removable media
      - polkit-kde-agent                                       # authentication agent
      - xdg-desktop-portal-hyprland                            # xdg desktop portal for hyprland
      - xdg-desktop-portal-gtk                                 # xdg desktop portal using gtk
      - qt5-imageformats                                       # for dolphin image thumbnails
      - ffmpegthumbs                                           # for dolphin video thumbnails
      - kde-cli-tools                                          # for dolphin file type defaults
      - libnotify                                              # for notifications
      - swaync                                                 # notification daemon
      - nwg-look                                               # gtk configuration tool
      - qt5ct                                                  # qt5 configuration tool
      - adw-gtk-theme-git                                      # libadwaita ported to GTK-3
      - qt6ct                                                  # qt6 configuration tool
      - kvantum                                                # svg based qt6 theme engine
      - kvantum-qt5                                            # svg based qt5 theme engine
      - qt5-wayland                                            # wayland support in qt5
      - qt6-wayland                                            # wayland support in qt6
      - dolphin                                                # kde file manager
      - ark                                                    # kde file archiver
      - fastfetch                                              # system information fetch tool
      - starship                                               # customizable shell prompt
    state: present
