---
- name: "Hyprland | {{ ansible_distribution }} | Install Hyprland and Utilites"
  kewlfft.aur.aur:
    use: yay
    name:
      - hyprland                                               # wlroots-based wayland compositor
      - dunst                                                  # notification daemon
      - rofi-wayland                                           # application launcher
      - ulauncher                                              # launcher / power menu
      - avizo                                                  # volume / brightness indicator
      - phinger-cursors                                        # cursor
      - waybar                                                 # system bar
      - ironbar-git                                                # system bar
      - swww                                                   # wallpaper backend engine
      - gtk-update-icon-cache
      - kuyen-icon-theme-git
      - waypaper                                               # wallpaper frontend GUI
      - hyprlock                                               # lock screen
      - hyperidle                                              # idle daemon
      # - swaylock-effects-git                                   # lock screen
      - wlogout                                                # logout menu
      - grimblast-git                                          # screenshot tool
      - wf-recorder                                            # Screen recording
      - hyprpicker                                             # color picker
      - slurp                                                  # region select for screenshot/screenshare
      - swappy                                                 # screenshot editor
      - clipse                                                 # clipboard manager
      - wl-clipboard                                           # system clipboard
      # - cliphist                                               # clipboard manager
      - sddm                                                   # display manager for KDE plasma
      - qt5-quickcontrols                                      # for sddm theme ui elements
      - qt5-quickcontrols2                                     # for sddm theme ui elements
      - qt5-graphicaleffects                                   # for sddm theme effects
      - pipewire                                               # audio/video server
      - pipewire-alsa                                          # pipewire alsa client
      - pipewire-audio                                         # pipewire audio client
      - pipewire-jack                                          # pipewire jack client
      - pipewire-pulse                                         # pipewire pulseaudio client
      - gst-plugin-pipewire                                    # pipewire gstreamer client
      - wireplumber                                            # pipewire session manager
      - playerctl                                              # media player controller
      # - pwvucontrol                                            # pipewire volume control
      - pavucontrol                                            # pulseaudio volume control
      - pamixer                                                # pulseaudio cli mixer
      - pactl                                                  # pulseaudio cli utility
      - networkmanager                                         # network manager
      - network-manager-applet                                 # network manager system tray utility
      - bluez                                                  # bluetooth protocol stack
      - bluez-utils                                            # bluetooth utility cli
      - blueman                                                # bluetooth manager gui
      - overskride
      - brightnessctl                                          # screen brightness control
      - udiskie                                                # manage removable media
      # - polkit-gnome
      - polkit-kde-agent                                       # authentication agent
      - xdg-desktop-portal-hyprland                            # xdg desktop portal for hyprland
      - xdg-desktop-portal-gtk                                 # xdg desktop portal using gtk
      - pacman-contrib                                         # for system update check
      - python-pyamdgpuinfo                                    # for amd gpu info
      - parallel                                               # for parallel processing
      - jq                                                     # for json processing
      - imagemagick                                            # for image processing
      - qt5-imageformats                                       # for dolphin image thumbnails
      - ffmpegthumbs                                           # for dolphin video thumbnails
      - kde-cli-tools                                          # for dolphin file type defaults
      - libnotify                                              # for notifications
      - nwg-look                                               # gtk configuration tool
      - qt5ct                                                  # qt5 configuration tool
      - adw-gtk-theme-git                                      # libadwaita ported to GTK-3
      - qt6ct                                                  # qt6 configuration tool
      - kvantum                                                # svg based qt6 theme engine
      - kvantum-qt5                                            # svg based qt5 theme engine
      - qt5-wayland                                            # wayland support in qt5
      - qt6-wayland                                            # wayland support in qt6
      - dolphin                                                # kde file manager
      - ark                                                    # kde file archiver
      - fastfetch                                              # system information fetch tool
      - starship                                               # customizable shell prompt
    state: present
