---
# tasks file for dev

- name: "DEV | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: dev_distribution_config

# Run distribution specific ansible task
- name: "DEV | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: dev_distribution_config.stat.exists
  ignore_errors: yes

# Run language specific ansible task
# - name: DEV | Python | Run Python Tasks
#   ansible.builtin.include_tasks: "python.yml"

# - name: DEV | Csharp | Run Python Tasks
#   ansible.builtin.include_tasks: "csharp.yml"
